### ISSUE TITLE
SPN figure is wrong?

### ISSUE THREAD

**Issue by utkarsh0902311047** [SPFlow/SPFlow#111]
### What did you expect to happen?

The child of a product node should be a sum node and vice-versa. This is what I have read about SPNs.

### What actually happened?

The figure shown has a product node as child of a product node. How is that possible?

### Steps to reproduce

The given code

### System Information

Google colab

### Installed Python Packages

spnflow

**Comment by steven-lang** [comment]
As long as the SPN validity is given, having product nodes as children of product nodes is fine (as well as having sum nodes as children of sum nodes). See e.g. the following decomposition:

$p(A,B,C) = p(A)  (p(B)  p(C))$

which can be represented as an SPN in the following graph:

```
         (x)
        /   \
      (A)   (x)
           /   \
         (B)   (C)
```
