### ISSUE TITLE
Help needed running the current dev_tensorly example

### ISSUE THREAD

**Issue by jschj** [SPFlow/SPFlow#150]
Hi,

this isn't really a bug. I just need some help running the basic example from the README in `dev_tensorly`.

I setup a new virtual environment (Python 3.11.6) and `pip install -e .`'ed in the cloned `SPFlow` directory.  When I try to run
```
from spflow.meta.data import Scope
import spflow.base.structure.spn as spn

model = spn.SumNode(
            children=[
                spn.ProductNode(
                    children=[
                        spn.Gaussian(Scope([0]), mean=-1.0, std=0.5),
                        spn.Gaussian(Scope([1]), mean=1.0, std=1.2),
                    ]),
                spn.ProductNode(
                    children=[
                        spn.Gaussian(Scope([0]), mean=2.5, std=1.0),
                        spn.Gaussian(Scope([1]), mean=1.0, std=0.7),
                    ])
            ],
            weights = [0.3, 0.7]
        )
```
I get the error `AttributeError: module 'spflow.base.structure.spn' has no attribute 'SumNode'`. The `__init__.py` files in the base subdirectory contain a lot of commented out import code. Uncommenting that leads to circular import problems.

When I try the tensorly backend I get the error that all nodes must have the same backend type (some are `numpy`, others are `pytorch`).

I'm a little confused and could need some help understanding the structure of the project.

Thanks in advance!

Update:
I just pulled the recent changes and it fixed the issues with the tensorly backend. However, the base backend issues still exist.

**Comment by braun-steven** [comment]
Hey Jschj, thanks for checking out SPFlow! We are currently rewriting the library from scratch with support for multiple backends (torch, tensorflow, jax, etc.). The code is almost feature-complete (some things are still missing here and there). When the last couple of missing features are implemented, we will have to restructure and clean up the package and update the README and the general documentation -- the `dev_tensorly` branch is a bit messy right now and not intended to be used (without warning). Just to let you know: the base and tensorly backend should be the same. For version 1.0.0 we use tensorly as our abstraction over the tensor operations provided by torch, tensorflow, jax, etc. So when the package restructuring is done it shouldn't be necessary to import from `base` or `tensorly` or anything, there will be a single unified way of importing modules.

In any case, here is how you can fix your example:

```
from spflow.meta.data import Scope
from spflow.base.structure.spn.nodes.sum_node import SumNode
from spflow.base.structure.spn.nodes.product_node import ProductNode
from spflow.base.structure.general.nodes.leaves.parametric.gaussian import Gaussian


model = SumNode(
            children=[
                ProductNode(
                    children=[
                        Gaussian(Scope([0]), mean=-1.0, std=0.5),
                        Gaussian(Scope([1]), mean=1.0, std=1.2),
                    ]),
                ProductNode(
                    children=[
                        Gaussian(Scope([0]), mean=2.5, std=1.0),
                        Gaussian(Scope([1]), mean=1.0, std=0.7),
                    ])
            ],
            weights = [0.3, 0.7]
        )
```

I'll close this issue -- if you have any other questions let me know!

Cheers :-)
