### ISSUE TITLE
Revisit Project Layout

### ISSUE THREAD

**Issue by felixdivo** [SPFlow/SPFlow#151]
We should follow the [common Python project layout](https://docs.python-guide.org/writing/structure/#sample-repository). In particular, I propose going for the following structure:

```text
.github/
.gitignore
.devcontainer/
<other config ...>

README.md
<other standalone documents like licenses, changelog, ...>

pyproject.toml // <-- here, we configure all tools to find the stuff defined below

spflow/
  base
  meta
  __init__.py
  ...

tests/
  ...
  __init__.py

docs/
  resources/  // <-- here, we can place images for the README, like logos
  ...
```

Ragarding the `docs/` folder, I'm not completely sure. We could just go for the [normal Sphinx folder structure](https://www.sphinx-doc.org/en/master/tutorial/getting-started.html#creating-the-documentation-layout) that we would add in #101. But if we want to keep more stuff like [`design-concept/`](https://github.com/SPFlow/SPFlow/tree/dev_tensorly/design-concept), we might need to add a folder for that. Or we integrate it into the Sphinx docs.

**Comment by braun-steven** [comment]
Agreed. I guess this should also happen only after we finalize all the implementation stuff.

**Comment by felixdivo** [comment]
> this should also happen only after we finalize all the implementation stuff

Yes, but before the review.

**Comment by braun-steven** [comment]
Woops, that reference was an accident, [d13b3a4](https://github.com/SPFlow/SPFlow/commit/d13b3a4f4055d118736818b85466c59ff25cb3b0) doesn't actually resolve this issue.
