### ISSUE TITLE
Add Codecov bot

### ISSUE THREAD

**Issue by braun-steven** [SPFlow/SPFlow#168]
Does it make sense to add the codecov bot? https://github.com/apps/codecov

@felixdivo do you have any experience with this in terms of helpfulness?

**Comment by felixdivo** [comment]
I think it is a useful thing to have. I creates a bit of noise though, since it comments ont the PR. I guess it's worth it. 🤷

**Comment by felixdivo** [comment]
As it is assigned to me, shall I add it?

**Comment by braun-steven** [comment]
Yep, feel free if you find time for it 🙂
