### ISSUE TITLE
Warnings in learn_parametric and bad results

### ISSUE THREAD

**Issue by Lapayo** [SPFlow/SPFlow#18]
Hey!
I am right now trying to learn a spn using a dataset with one categorical label and 20 continuous variables, but I have some problems getting the spn to learn.

I often get warnings like
```
X scores are null at iteration 0
  warnings.warn('X scores are null at iteration %s' % k)
```
and
```
invalid value encountered in true_divide
  c /= stddev[:, None]
```
when calling learn_parametric / learn_classifier. 
After updating from 25988df to HEAD ( a1ce6d3 ) I get even more warnings regarding the "X scores".

The code used is:
```
ds_context = Context(parametric_types=[Categorical] + [Gaussian] * 20).add_domains(train_data)
pspn = learn_classifier(train_data, ds_context, learn_parametric, 0, min_instances_slice=20)
```

Additionally the classification results gathered from such a SPN is not very good - but I dont know if this is related to the warnings or if this another problem. (e.g. 72% Acc. compared to 92% with a logistic regression)

What might be the problem, when encountering such issues? Is this a dataset related problem? Or am I using wrong parameters? Or do those messages have no meaning and I can safely ignore them?

I would very much appreciate any help!

**Comment by Lapayo** [comment]
I have also created a csv with some data and a minimal example in a jupyter notebook, that gives the described warnings.
Maybe this is helpful in case there is something to debug.
I would also like to help debugging and fixing if there are some problems here, that are not data related, but I would need some directions on where the error might be or where to start looking.
[spn_training_failed.zip](https://github.com/SPFlow/SPFlow/files/2675869/spn_training_failed.zip)

**Comment by Lapayo** [comment]
The bad accuracy seems to be (at least partially) caused by https://github.com/SPFlow/SPFlow/issues/21

However I am still curious if there is an issue with those printed errors.

**Comment by alejandromolinaml** [comment]
Great catch!

I'm pushing a fix for this.
