### ISSUE TITLE
MPE bottom-up mixing log-likelihoods with likelihoods

### ISSUE THREAD

**Issue by Lapayo** [SPFlow/SPFlow#21]
I probably found an issue regarding the MPE code.
It looks like log likelihoods (e.g. sum and product) are mixed with "normal" likelihoods in the bottom-up pass. (At least for categorical and gaussian leaves)
This leads to an undefined behavior when using MPE e.g. to classify data.

I also prepared a fix that should correct the problem at least for categorical and gaussian leaves.
Any thoughts on this?

**Comment by alejandromolinaml** [comment]
good Catch! 

I issued a fix, check commit  fe4e8f3  
please add yourself as a collaborator in the readme.md
