### ISSUE TITLE
add_domain in Base.Context does not work with missing values

### ISSUE THREAD

**Issue by cvoelcker** [SPFlow/SPFlow#45]
### Description

The add_domains method in the Context class calculates the domains for input data. In the presence of missing data (in this case represented by nan values, as expected by the learn_mspn_with_missing function), the function breaks down due to the implementation of np.min

#### Expected behavior:

The domain ignores missing value

#### Encountered behavior:

np.min and np.max return np.nan for an array which contains nan values

### Additional Information

This behavior can be changed by using np.nanmin and np.nanmax in the function. This should not introduce a breaking change (to the best of my knowledge).

- Operating System:
- Python Version:

**Comment by alejandromolinaml** [comment]
done
