### ISSUE TITLE
RAT_SPN Sample Function "Does Not Work"

### ISSUE THREAD

**Issue by n2cholas** [SPFlow/SPFlow#62]
### Description
The [sample function](https://github.com/SPFlow/SPFlow/blob/master/src/spn/experiments/RandomSPNs/RAT_SPN.py#L495-L507) for RAT_SPN says `# Does not work currently!`. What is wrong with it?

It was introduced in this commit: https://github.com/SPFlow/SPFlow/commit/29282bbce21ff7abc3480aab93d482b4388e8bf1

**Comment by felixdivo** [comment]
This is unclear to me as well. However, current efforts to modernize re repo do not include porting this function.
