### ISSUE TITLE
Migrate from TF1 to TF2

### ISSUE THREAD

**Issue by RenatoGeh** [SPFlow/SPFlow#70]
### Description

SPFlow uses the old 1.14 version of Tensorflow, but since Tensorflow 2 is already out, SPFlow should make use of the new features and syntax of TF2.

We could alternatively reach a compromise and have support for both versions.

A [patch](https://aur.archlinux.org/cgit/aur.git/tree/tf2.patch?h=python-spflow) for the Arch Linux package already exists to convert a portion of SPFlow to TF2 runnable code, but since the test coverage is hardly comprehensive and some of the existing tests require datasets that are not present in the repository itself, it is not guaranteed to provide a reliable refactoring.

#### Expected behavior:

SPFlow should support TF2.

#### Encountered behavior:

SPFlow does not support TF2.

### Additional Information

- Operating System: Linux
- Python Version: 3.8

**Comment by braun-steven** [comment]
Clsoing this as v1.0.0 will support tf 2.x
