### ISSUE TITLE
Unable to Reproduce Example Visualization

### ISSUE THREAD

**Issue by zecevic-matej** [SPFlow/SPFlow#89]
### Description

Following the beginning of the README documentation and running 
```
from spn.structure.leaves.parametric.Parametric import Categorical

spn = 0.4 * (Categorical(p=[0.2, 0.8], scope=0) *
             (0.3 * (Categorical(p=[0.3, 0.7], scope=1) *
                     Categorical(p=[0.4, 0.6], scope=2))
            + 0.7 * (Categorical(p=[0.5, 0.5], scope=1) *
                     Categorical(p=[0.6, 0.4], scope=2)))) \
    + 0.6 * (Categorical(p=[0.2, 0.8], scope=0) *
             Categorical(p=[0.3, 0.7], scope=1) *
             Categorical(p=[0.4, 0.6], scope=2))
```
followed by
```
from spn.io.Graphics import plot_spn

plot_spn(spn, 'basicspn.png')
```
results in (an) error(s).

#### Expected behavior:

Should create the visualization file `basicspn.png`.

#### Encountered behavior:

1st error is: `FileNotFoundError: [Errno 2] "dot" not found in path.` 
and can be resolved by running `brew install graphviz`

2nd error is: `TypeError: draw_networkx_edge_labels() got an unexpected keyword argument 'clip_on'`
unresolved

### Additional Information

- Operating System: MacOS Big Sur 11.0 Beta
- Python Version: 3.7

**Comment by zecevic-matej** [comment]
I guess the problem might come from `networkx` being not in the right version i.e., me having a newer versions in which the API has changed. The `requirements.txt` does not restrict versions for `networkx`.

**Comment by hayesall** [comment]
Can you include your `networkx` version?

`clip_on` is listed in the [2.5 release of networkx](https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edge_labels.html), but I skimmed their code and the parameter name does not appear to be used in the code.

This might have been tweaked in https://github.com/networkx/networkx/pull/4182

**Comment by hayesall** [comment]
It looks like there were several behind-the-scenes changes for how keyword arguments were handled between the previous few `networkx` releases. More details in the PR.

Thank you for reporting!
