### ISSUE TITLE
Bug in algorithms/Condition.py

### ISSUE THREAD

**Issue by MoritzKulessa** [SPFlow/SPFlow#93]
### Description

Hi :), there is a bug in "algorithms/Condition.py". Conditioning does not work, if the complete scope of a product node needs to be pruned. The following code fails:

<pre><code>
import numpy as np
from spn.structure.leaves.parametric.Parametric import Categorical
from spn.structure.Base import assign_ids, rebuild_scopes_bottom_up
from spn.algorithms import Condition

sub_spn1 = Categorical(p=[0.5, 0.5], scope=0) * Categorical(p=[0.5, 0.5], scope=1)
sub_spn2 = Categorical(p=[0.5, 0.5], scope=0) * Categorical(p=[0.5, 0.5], scope=1)
sub_spn3 = 0.5 * sub_spn1 + 0.5 * sub_spn2
sub_spn4 = Categorical(p=[0.5, 0.5], scope=2) * sub_spn3
sub_spn5 = Categorical(p=[0.5, 0.5], scope=0) * Categorical(p=[0.5, 0.5], scope=1) * Categorical(p=[0.5, 0.5], scope=2)
spn = 0.5 * sub_spn4 + 0.5 * sub_spn5

assign_ids(spn)
rebuild_scopes_bottom_up(spn)

evidence = np.array([[0, 0, np.nan]])
c_spn = Condition.condition(spn, evidence)

from spn.io.Text import spn_to_str_ref_graph
print(spn_to_str_ref_graph(c_spn))
</code></pre>

#### Expected behavior:
<pre><code>
SumNode_0 SumNode(0.5*CategoricalNode_1, 0.5*CategoricalNode_2){
	CategoricalNode_1 Categorical(V2|p=[0.5, 0.5])
	CategoricalNode_2 Categorical(V2|p=[0.5, 0.5])
	}
</code></pre>

#### Encountered behavior:

<pre><code>
C:\Users\Moritz\Miniconda3\envs\spn\lib\site-packages\spn\algorithms\Condition.py:46: RuntimeWarning: divide by zero encountered in log
  return None, np.log(sum(probs))
Traceback (most recent call last):
  File "C:/pyCharm/NSS/src/_other/test_condition.py", line 19, in <module>
    c_spn = Condition.condition(spn, evidence)
  File "C:\Users\Moritz\Miniconda3\envs\spn\lib\site-packages\spn\algorithms\Condition.py", line 65, in condition
    return Prune(new_root)
  File "C:\Users\Moritz\Miniconda3\envs\spn\lib\site-packages\spn\algorithms\TransformStructure.py", line 39, in Prune
    assert v, err
AssertionError: node 4 has no scope
</code></pre>

### Possible Solution

From my point of view, the problem can be solved by updating the code for "prod_condition(...)" to the following:

<pre><code>
def prod_condition(node, children, input_vals=None, scope=None):
    if not scope.intersection(node.scope):
        return Copy(node), 0
    new_node = Product()
    new_node.scope = list(set(node.scope) - scope)
    probability = 0

    for c in children:
        if c[0]:
            new_node.children.append(c[0])
        probability += float(c[1])

    if len(new_node.children) == 0:
        return None, probability

    return new_node, probability
</code></pre>

### Additional Information

Moreover, it might be handy to have a version of "Condition" which does not use the logarithm to be able to also work with 0 probability. 

- Operating System: Windows
- Python Version: 3.7

**Comment by braun-steven** [comment]
Thanks for your contribution! We're rewriting the library from scratch with support for multiple execution backends without reusing any of the old code. Therefore, this issue won't persist in the upcoming v1.0.0 release.
