### ISSUE TITLE
Rename python submodule to something more appropriate

### ISSUE THREAD

**Issue by steven-lang** [SPFlow/SPFlow#99]
I think the name `python` of the `spflow.python` submodule is not a good choice. Everything in `spflow` is python based, i.e. we don't have any c/c++/other extension languages. We rather wanted to indicate that `spflow.python` contains the "naive"/"base" implementation that doesn't make any use of optimized libraries such as tensorflow, pytorch, or jax.

One option would be to rename this submodule to something more appropriate. I'm open to suggestions, some ideas could be:
- base
- naive
- plain

Another option could be to simply move everything in `spflow.python` into `spflow` itself. What do you think? @pdeibert @bewit @HuyDC.

**Comment by pdeibert** [comment]
Submodule for base implementation was renamed to `spflow.base`
